include: package:very_good_analysis/analysis_options.5.0.0.yaml

analyzer:
  exclude:
    - "lib/**/*.g.dart"
    - "lib/**/*.freezed.dart"
    - "lib/**/*.mocks.dart"
    - "lib/l10n/*.dart"
    - "lib/firebase_options.dart"

linter:
  rules:
    public_member_api_docs: false

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    number-of-parameters: 4
    maximum-nesting-level: 5
    depth-of-inheritance-tree: 5
    number-of-added-methods: 10
    number-of-overridden-methods: 10
    number-of-implemented-interfaces: 5
    number-of-methods: 10
    coupling-between-object-classes: 12
    response-for-class: 55
    weighted-methods-per-class: 35
    maintainability-index: 70
    tight-class-cohesion: 0.33
    weight-of-class: 0.33
    lines-of-executable-code: 100
    number-of-imports: 10
    number-of-external-imports: 5
    technical-debt:
      threshold: 1
      todo-cost: 161
      ignore-cost: 320
      ignore-for-file-cost: 396
      as-dynamic-cost: 322
      deprecated-annotations-cost: 37
      file-nullsafety-migration-cost: 41
      unit-type: "USD"

  metrics-exclude:
    - test/**

  rules:
    - avoid-bloc-public-methods
    - avoid-cubits
    - avoid-passing-bloc-to-bloc
    - check-is-not-closed-after-async-gap
    - prefer-correct-bloc-provider
    - prefer-multi-bloc-provider
    - avoid-ignoring-return-values:
        exclude:
          - test/**
    - avoid-global-state
    - avoid-identical-exception-handling-blocks
    - avoid-long-files:
        max-length: 500
    - avoid-duplicate-named-imports
    - avoid-duplicate-patterns
    - avoid-equal-expressions
    - avoid-double-slash-imports
    - avoid-duplicate-exports
    - avoid-importing-entrypoint-exports:
        only-in-src: true
    - avoid-bottom-type-in-records
    - avoid-bottom-type-in-patterns
    - avoid-cascade-after-if-null
    - arguments-ordering:
        child-last: true
    - avoid-accessing-collections-by-constant-index
    - avoid-banned-file-names:
        entries:
          - .*example.dart
    # - avoid-accessing-other-classes-private-members
    # - avoid-dynamic
    # - avoid-passing-async-when-sync-expected
    # - avoid-redundant-async
    - avoid-async-call-in-sync-function
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unrelated-type-assertions
    - avoid-unused-parameters:
        ignore-inline-functions: false
    - avoid-nested-conditional-expressions
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
    - prefer-moving-to-variable:
        allowed-duplicated-chains: 3
    - prefer-match-file-name:
        exclude:
          - test/**
    - avoid-collapsible-if
    - avoid-redundant-else
    - avoid-incomplete-copy-with
    - avoid-self-compare
    - avoid-self-assignment
    # - avoid-unnecessary-nullable-return-type
    - avoid-unrelated-type-casts
    - prefer-declaring-const-constructor:
        allow-one: true
    # - avoid-barrel-files